### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by sosoneo** [saitjr/wordpress-api#1]
能不能用你的这个api 做个小的app

**Comment by saitjr** [comment]
可以

**Comment by sosoneo** [comment]
你那个借口该怎么拼接啊

**Comment by saitjr** [comment]
有接口文档的
http://tangjr.gitbooks.io/brighttj-api/content/
使用POST和GET请求都可以

比如获取文章列表的接口地址是：http://www.brighttj.com/api/index.php/api/article/articleList
使用GET就直接在URL后面加   ?page=1&pageSize=20
使用POST就直接放大body里面传参就行

**Comment by sosoneo** [comment]
ok  多谢了呢

**Comment by sosoneo** [comment]
大哥，最近准备去面试，做完这个能不能上架，实在不行我面试完我就给你下架了。如果要上架在哪里写你的相关信息。

**Comment by saitjr** [comment]
可以上架，在软件描述里面写一下相关信息就好

**Comment by saitjr** [comment]
我把接口修改了，并新增了用户信息、热门文章接口。
接口地址没变，但是json结构变了，如有需要，请更新json解析。
