### ISSUE TITLE
中文能否不转换成Unicode编码？

### ISSUE THREAD

**Issue by jarvanh** [saitjr/wordpress-api#3]
你好，我发现返回的数据中文都是转换成Unicode编码，能否保持中文呢？

例如：

http://www.brighttj.com/api/index.php/api/article/articleById
获取的数据是：
{"data":{},"msg":"\u6587\u7ae0id\u65e0\u6548","status":0}

**Comment by saitjr** [comment]
Unicode 应该更通用一点
